# Contents of application-dev.properties
spring.jpa.show-sql=true
spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/brutshop
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.data.redis.url=redis://localhost:6379
