spring.application.name=e-commerce

# Currect Active Profile (switch to dev to run locally [dev/prod])
# spring.profiles.active=dev

# JPA
spring.jpa.defer-datasource-initialization=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Image Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# PostgresDB (via Session Pooler)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

#Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.data-source-properties.cachePrepStmts=false
spring.datasource.hikari.data-source-properties.useServerPrepStmts=false
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=0
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=0

# JWT
jwt.secret=thisIsMyVeryStrongSuperSecretKey123!
jwt.expiration=900000
jwt.refresh.expiration=604800000

spring.cache.type=redis
spring.data.redis.url=${REDIS_URL}
spring.cache.redis.time-to-live=60m
