name: Keep Alive Ping
on:
  schedule:
    # Runs at 2:00 AM UTC every day.
    - cron: '0 2 * * *'
  workflow_dispatch: # Run this workflow manually from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the deployed service to keep it alive
        run: curl -s "https://springboot-ecommerce-latest-ctgu.onrender.com/api/products" > /dev/null